include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: false
    require_trailing_commas: true
    always_declare_return_types: true
    avoid_void_async: true
    avoid_dynamic_calls: true

    # const
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_declarations: true

analyzer:
  exclude:
    - '**.freezed.dart'
    - '**.g.dart'
    - '**.gr.dart'
  plugins:
    # broken currently and may not get fixed
    # https://github.com/simolus3/drift/issues/2342
    # - drift

    # also broken but only recently reported
    # https://github.com/rrousselGit/riverpod/issues/2180
    # - custom_lint 
